#Requires -Version 7.0
<#
.SYNOPSIS
    Prompts for a password and writes it encrypted to
    encrypted_pw\encryptedString_<Label>.txt using the $key from globalvars.ps1.

.DESCRIPTION
    Read-Host -AsSecureString — the password never appears as plaintext in
    a variable, never on the command line, never in the console buffer.
    ConvertFrom-SecureString encrypts it with the random AES key in
    globalvars.ps1 (generated by tools\New-PoshAesKey.ps1).

    To read it back in a script:
        . globalvars.ps1
        $cipher = (Get-Content "$PoshEncryptedDir\encryptedString_<Label>.txt" -Raw).Trim()
        $secStr = ConvertTo-SecureString -String $cipher -Key $key
        $cred   = [PSCredential]::new('DOMAIN\<user>', $secStr)

.PARAMETER Label
    Identifier used in the filename. Lowercase + dashes / underscores
    recommended.

.PARAMETER Force
    Overwrite an existing file with the same Label.

.EXAMPLE
    .\tools\Set-PoshSecret.ps1 -Label 'ad_adsread'
#>
[CmdletBinding(SupportsShouldProcess)]
[Diagnostics.CodeAnalysis.SuppressMessageAttribute('PSAvoidUsingWriteHost', '',
    Justification = 'Interactive setup tool — coloured Write-Host output is intended.')]
param(
    [Parameter(Mandatory)]
    [ValidatePattern('^[A-Za-z0-9_-]+$')]
    [string] $Label,
    [switch] $Force
)

$ErrorActionPreference = 'Stop'

# Load $key + $PoshEncryptedDir from the central template.
$globalvars = Join-Path (Split-Path -Parent $PSScriptRoot) 'globalvars.ps1'
if (-not (Test-Path -LiteralPath $globalvars -PathType Leaf)) {
    Write-Host "ABORT: globalvars.ps1 not found at $globalvars" -ForegroundColor Red
    exit 1
}
. $globalvars

if (($key | Where-Object { $_ -ne 0 }).Count -eq 0) {
    Write-Host 'ABORT: $key in globalvars.ps1 is all zeros (placeholder).' -ForegroundColor Red
    Write-Host '       Run tools\New-PoshAesKey.ps1 first to generate a real key.'
    exit 1
}

if (-not (Test-Path -LiteralPath $PoshEncryptedDir -PathType Container)) {
    $null = New-Item -ItemType Directory -Path $PoshEncryptedDir -Force
}

$outFile = Join-Path $PoshEncryptedDir ("encryptedString_$Label.txt")
if ((Test-Path -LiteralPath $outFile -PathType Leaf) -and -not $Force) {
    Write-Host "ABORT: $outFile already exists. Re-run with -Force to overwrite." -ForegroundColor Red
    exit 1
}

$pw = Read-Host -Prompt ("Password for '{0}'" -f $Label) -AsSecureString
$cipher = ConvertFrom-SecureString -SecureString $pw -Key $key

if ($PSCmdlet.ShouldProcess($outFile, 'Write encrypted secret')) {
    [System.IO.File]::WriteAllText($outFile, $cipher, [System.Text.UTF8Encoding]::new($false))
    Write-Host "OK: stored at $outFile" -ForegroundColor Green
}
